name: MysticGuis
author: QuickScythe
version: ALPHA
description: Custom GUIs brought to you by the creator of MysticCloud.net
api-version: 1.16
api: Spigot
main: net.mysticcloud.spigot.guis.MysticPlugin
soft-depend:
- Vault
commands:
   inventory:
      usage: /inventory <inventory>
      aliases:
      - inv